{% set name = "qpot" %}
{% set version = "0.0.2" %}
{% set sha256 = "3b4b4124de92b4dd82d40b1cfd046316277ecf98d54b75a33dc95f8d85d81538" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/QPot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/QPot  # [unix]
    - test -f ${PREFIX}/include/QPot/Static.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/QPot/QPotConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\QPot\Static.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\QPotConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/QPot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to keep track of a sequential potential energy landscape.
  description: Library to keep track of a sequential potential energy landscape.
  doc_url: https://github.com/tdegeus/QPot
  dev_url: https://github.com/tdegeus/QPot

extra:
  recipe-maintainers:
    - tdegeus
